/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class github_com_stonevoicer_VoicerUtil */

#ifndef _Included_github_com_stonevoicer_VoicerUtil
#define _Included_github_com_stonevoicer_VoicerUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef github_com_stonevoicer_VoicerUtil_MODE_NORMAL
#define github_com_stonevoicer_VoicerUtil_MODE_NORMAL 0L
#undef github_com_stonevoicer_VoicerUtil_MODE_LUOLI
#define github_com_stonevoicer_VoicerUtil_MODE_LUOLI 1L
#undef github_com_stonevoicer_VoicerUtil_MODE_DASHU
#define github_com_stonevoicer_VoicerUtil_MODE_DASHU 2L
#undef github_com_stonevoicer_VoicerUtil_MODE_JINGSONG
#define github_com_stonevoicer_VoicerUtil_MODE_JINGSONG 3L
#undef github_com_stonevoicer_VoicerUtil_MODE_GAOGUAI
#define github_com_stonevoicer_VoicerUtil_MODE_GAOGUAI 4L
#undef github_com_stonevoicer_VoicerUtil_MODE_KONGLING
#define github_com_stonevoicer_VoicerUtil_MODE_KONGLING 5L
/*
 * Class:     github_com_stonevoicer_VoicerUtil
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_github_com_stonevoicer_VoicerUtil_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
